version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: fitmind-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitmind
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fitmind-backend
    restart: unless-stopped
    env_file:
      - ./api-backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  db_data:
